#设置各种概率,不可以为负数,概率为总和/单个概率

#时之沙主词条概率
shizhisha : [
  27,   #攻击力
  27,   #充能
  26,   #精通
  10,   #防御力
  10    #生命值
]

#空之杯主词条概率
kongzhibei : [
  19,   #攻击力
  3,    #精通
  19,   #防御力
  19,   #生命值
  5,    #草元素伤害加成
  5,    #雷元素伤害加成
  5,    #风元素伤害加成
  5,    #岩元素伤害加成
  5,    #火元素伤害加成
  5,    #水元素伤害加成
  5,    #冰元素伤害加成
  5     #物理元素伤害加成
]

#理之冠主词条概率
lizhiguan : [
  22,   #攻击力
  4,    #精通
  22,   #防御力
  22,   #生命值
  10,   #暴击率
  10,   #暴击伤害
  10    #治疗加成
]

#初始词条数量概率
citiao : [
  80,   #三词条
  20    #四词条
]

#各个部位掉落概率
buwei : [
  20,   #生之花
  20,   #死之羽
  20,   #时之沙
  20,   #空之杯
  20    #理之冠
]

#副词条出现概率
fucitiao : [
  8,    #暴击率
  8,    #暴击伤害
  10,   #攻击力
  10,   #精通
  10,   #生命值
  10,   #防御力
  10,   #充能
  12,   #小攻击 
  11,   #小生命
  11,   #小防御
]

#强化档位概率
qianghua : [
  25,   #第一档最小值 比如5.4爆伤
  25,   #第二档
  25,   #第三档
  25    #第四档最大值 比如7.8爆伤
]

#副词条强化概率   
#每次随机四个副词条,想要那个强化概率高点可以把数字设置高一点,或者把别的设置低
fucitiaoqianghua : [
  25,   #暴击率
  25,   #暴击伤害
  25,   #攻击力
  25,   #精通
  25,   #生命值
  25,   #防御力
  25,   #充能
  25,   #小攻击 
  25,   #小生命
  25,   #小防御
]


#每次刷圣遗物的cd,单位为秒,为0则无cd
cd : 60